server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:student-db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  threads:
    virtual:
      enabled: true
  application:
    name: student-management-system
  output:
    ansi:
      enabled: ALWAYS

#logging:
#  level:
#    org:
#      springframework: DEBUG

security:
  authorization:
    paths:

      # Auth-Service

      - path: /auth-service/sign-up
        method: POST
        roles: []
      - path: /auth-service/sign-in
        method: POST
        roles: []
      - path: /auth-service/log-out
        method: POST
        roles: []
      - path: /auth-service/validate-access-token/**
        method: POST
        roles: []
      - path: /auth-service/refresh-token/**
        method: POST
        roles: []
      - path: /auth-service/partial-update/**
        method: PATCH
        roles:
          - ROLE_ADMIN
          - ROLE_STUDENT

      # Student-Service
      - path: /student-service
        method: POST
        roles:
          - ROLE_ADMIN
      - path: /student-service
        method: GET
        roles:
          - ROLE_ADMIN

      # Subject-Service
      - path: /subject-service/create
        method: POST
        roles:
          - ROLE_ADMIN
